version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kanbanuser
      - POSTGRES_PASSWORD=kanbanpass
      - POSTGRES_DB=kanban
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-net

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    networks:
      - app-net

volumes:
  pgdata:
    driver: local
