version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-net

  app:
    build: .
    container_name: kanban
    restart: always
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    networks:
      - app-net

volumes:
  pgdata:
    driver: local
